version: 0.2

env:
  shell: bash

phases:
  install:
    runtime-versions:
      nodejs: 12

  pre_build:
    commands:
      - ./scripts/ecr-login.sh
      - . ./scripts/codebuild-extras.sh

  build:
    commands:
      - ./scripts/build-docker-images.sh $REPOSITORY_URI $CODEBUILD_GIT_COMMIT

  post_build:
    commands:
      - ./scripts/push-docker-images.sh $REPOSITORY_URI $CODEBUILD_GIT_COMMIT
