[package]
name = "decrs"
version = "0.1.0"
edition = "2018"

[dependencies]
bytes = "1.1.0"
base64 = "0.13.0"
tokio = "1.16.0"
rusoto_core = "0.47.0"
rusoto_kms = "0.47.0"
openssl = { version = "0.10.38", features = ["vendored"] }