Description: CICD Pipeline for Decrs
Parameters:
  GithubToken:
    Type: String
    NoEcho: true
    Description: OAuth token for the Github organization.  Needs read/write access to repos and repo hooks

  GithubOwner:
    Type: String
    Description: Owner of the github repository to track

  GithubRepo:
    Type: String
    Description: Name of the github repository to track

  GithubBranch:
    Type: String
    Description: Name of the github branch to track

  PipelineDefinitionBucket:
    Type: String
    Description: Bucket name where the pipeline definition is located

  PipelineDefinitionKey:
    Type: String
    Description: Key name where the pipeline definition is located

Resources:
  DockerRepo:
    Type: AWS::ECR::PublicRepository
    Properties:
      RepositoryName: decrs
      RepositoryPolicyText:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - ecr-public:GetAuthorizationToken
              - sts:GetServiceBearerToken
            Principal: 
              AWS: !Ref AWS::AccountId
          - Effect: Allow
            Action:
              - ecr-public:GetDownloadUrlForLayer
              - ecr-public:BatchGetImage
              - ecr-public:BatchCheckLayerAvailability
              - ecr-public:ListImages
            Principal: "*"

  BuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: !Sub ${AWS::StackName}-build
      BadgeEnabled: true
      ServiceRole: !ImportValue cfn-utilities:BuilderRoleArn
      EncryptionKey: !ImportValue cfn-utilities:ArtifactKeyArn
      Environment:
        PrivilegedMode: true
        Image: aws/codebuild/standard:4.0
        ComputeType: BUILD_GENERAL1_SMALL
        EnvironmentVariables:
          - Name: REPOSITORY_URI
            Value: !Sub public.ecr.aws/cythral/${DockerRepo}
        Type: LINUX_CONTAINER
      Cache:
        Type: LOCAL
        Modes:
          - LOCAL_DOCKER_LAYER_CACHE
      Artifacts:
        Type: NO_ARTIFACTS
      Source:
        Type: GITHUB
        Location: !Sub https://github.com/${GithubOwner}/${GithubRepo}.git
        ReportBuildStatus: true
        BuildStatusConfig:
          Context: build
          TargetUrl: !Sub https://sso.brigh.id/start/shared?destination=https://console.aws.amazon.com/codesuite/codebuild/${AWS::AccountId}/projects/${AWS::StackName}-build/build/$CODEBUILD_BUILD_ID/?region=${AWS::Region}

  StateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      RoleArn: !ImportValue cfn-utilities:MasterRoleArn
      StateMachineName: !Sub ${AWS::StackName}-pipeline
      DefinitionS3Location:
        Bucket: !Ref PipelineDefinitionBucket
        Key: !Ref PipelineDefinitionKey
      DefinitionSubstitutions:
        GithubRepo: !Ref GithubRepo
        GithubOwner: !Ref GithubOwner
        BuildProject: !Ref BuildProject
        SharedRoleArn: !ImportValue cfn-utilities:MasterRoleArn
        AccountId: !Ref AWS::AccountId
    Metadata:
      cfn-lint:
        config:
          ignore_checks:
            - E3002
            - E3003