<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AWSSDK.CloudFormation" Version="4.0.102.6" />
    <PackageReference Include="AWSSDK.ECR" Version="4.0.101.5" />
    <PackageReference Include="AWSSDK.ECRPublic" Version="4.0.100.13" />
    <PackageReference Include="AWSSDK.KeyManagementService" Version="4.0.100.13" />
  </ItemGroup>
</Project>