<Project Sdk="Microsoft.NET.Sdk">
  <ItemGroup>
    <PackageReference Include="AWSSDK.CloudFormation" Version="4.0.103" />
    <PackageReference Include="AWSSDK.ECR" Version="4.0.101.8" />
    <PackageReference Include="AWSSDK.ECRPublic" Version="4.0.100.16" />
    <PackageReference Include="AWSSDK.KeyManagementService" Version="4.0.100.16" />
  </ItemGroup>
</Project>